#
# Cookie constants
#
REMEMBER_COOKIE_REFRESH_EACH_REQUEST = "REMEMBER_COOKIE_REFRESH_EACH_REQUEST"

#
# Session constants
#
REMEMBER_SESSION_KEY = "_remember"
SET_SESSION = "set"
CLEAR_SESSION = "clear"
SESSION_PROTECTION = "SESSION_PROTECTION"
